min_max: "Le champ %s doit être compris entre %s et %s caractères"
min: "Le champ %s doit être supérieur ou égal à %s caractères"
max: "Le champ %s doit être inférieur ou égal à %s caractères"
email: "Veuillez renseigner un email valide"
string: "Veuillez renseigner une chaine de type alphanumérique"
int: "Veuillez renseigner un nombre"
date: "Le format de votre date n'est pas valide"
repeated: "Les valeurs de '%s' doivent être identiques"
required: "Le champ %s doit être renseigné"
unique: "Le valeur de '%s' est déjà connu de notre base de donnée. Renseignez une nouvelle valeur."
auth: "L'email renseigné n'existe pas ou le mot de passe saisie n'est pas correcte."